version: '3.8'

services:
  web:
    build: ./backend
    container_name: backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8080:8080
    env_file:
      - ./backend/.local.env
  # db:
  #   image:'mongo:latest'
  #   env_file:
  #     - ./local.env
