version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8080:8080
    env_file:
      - ./backend/.local.env

  frontend:
    container_name: frontend
    build: ./frontend
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - './frontend:/app:cached'
      # - './frontend/node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=development
